Repository stolostron/acm-operator-bundle, pull requests merged in 2025-08, with the labels that each got.

#377 release 2.13 images
  config/acm-manifest-gen-config.json
Labels: lgtm, approved

#385 Latest snapshot from acm that should have pushed to acm-d
  BUILD-NUMBER
  Dockerfile
  debug/workflow-vars
  extras/2.15.0.json
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.15.0-12.clusterserviceversion.yaml
Labels: approved

#401 New build request
  BUILD-NUMBER
  Dockerfile
  debug/workflow-vars
  extras/2.15.0.json
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.15.0-18.clusterserviceversion.yaml
Labels: approved

#413 Manually updated snapshot for ACM 2.11
  BUILD-NUMBER
  Dockerfile
  debug/workflow-vars
  extras/2.11.0.json
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.11.0-2.clusterserviceversion.yaml
Labels: approved

#416 [release-2.11] Updated .tekton files configurations
  .tekton/acm-operator-bundle-acm-211-pull-request.yaml
  .tekton/acm-operator-bundle-acm-211-push.yaml
  BUILD-NUMBER
  Dockerfile
  debug/workflow-vars
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.11.0-3.clusterserviceversion.yaml
Labels: approved

#415 Manually updated snapshot for ACM 2.13
  BUILD-NUMBER
  Dockerfile
  config/acm-manifest-gen-config.json
  debug/workflow-vars
  extras/2.13.0.json
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.13.0-2.clusterserviceversion.yaml
Labels: approved, do-not-merge/hold

#418 Updated postgresql-13 tag in acm-manifest-gen-config
  BUILD-NUMBER
  Dockerfile
  config/acm-manifest-gen-config.json
  debug/workflow-vars
  extras/2.11.0.json
  latest-snapshot.yaml
  manifests/advanced-cluster-management.v2.11.0-5.clusterserviceversion.yaml
Labels: approved
